version: "3.7"
services:
  app:
    build: ./app
    deploy:
      replicas: 3
    environment:
       LISTENING_HOST: 0.0.0.0
       LISTENING_PORT: 5000
       DB_NAME: testdb
       DB_HOST: db
       MYSQL_DB_USER: root
       DB_PASSWORD: root
       REDIS_HOST: redis
    links:
      - db
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: mydb
      #MYSQL_USER: test
      #MYSQL_PASSWORD: test1234
    volumes:
      - ./docker/data/db:/var/lib/mydb
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    depends_on:
      - app
